#include "params.h"

PARAM_DEFINE_FLOAT(YONA_ROLL_P, 2.0f);
PARAM_DEFINE_FLOAT(YONA_ROLL_I, 0.01f);
PARAM_DEFINE_FLOAT(YONA_ROLL_D, 0.001f);

PARAM_DEFINE_FLOAT(YONA_PITCH_P, 2.0f);
PARAM_DEFINE_FLOAT(YONA_PITCH_I, 0.01f);
PARAM_DEFINE_FLOAT(YONA_PITCH_D, 0.001f);

PARAM_DEFINE_FLOAT(YONA_YAW_P, 3.0f);
PARAM_DEFINE_FLOAT(YONA_YAW_I, 0.01f);
PARAM_DEFINE_FLOAT(YONA_YAW_D, 0.001f);

PARAM_DEFINE_FLOAT(YONA_THRUST_P, 0.1f);
PARAM_DEFINE_FLOAT(YONA_THRUST_I, 0.01f);
PARAM_DEFINE_FLOAT(YONA_THRUST_D, 0.001f);
